name: baby_app
description: "baby_app"

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  crypto: ^3.0.3
  device_info_plus: ^10.1.2
  dio: ^5.5.0+1
  encrypt: ^5.0.3
  json_annotation: ^4.9.0
  path_provider: ^2.1.4
  shelf_proxy: ^1.0.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.4.0
  flutter_cache_manager: any
  path: any
  get: ^4.7.2
  flutter_udid: ^3.0.0
  hive_ce: ^2.10.1
  # hive: ^2.2.3
  hive_ce_flutter: ^2.2.0
  # hive_flutter: ^1.1.0
  uuid: ^4.4.2
  flutter_screenutil: ^5.9.3
  logger: ^2.4.0
  infinite_scroll_pagination: ^4.1.0
  lazy_load_indexed_stack: ^1.1.0
  carousel_slider: ^5.0.0
  universal_html: ^2.2.4
  url_launcher: ^6.3.0
  video_player: ^2.9.1
  easy_refresh: ^3.4.0
  visibility_detector: ^0.4.0+2
  buttons_tabbar: ^1.3.15
  flutter_staggered_grid_view: ^0.7.0
  easy_rich_text: ^2.1.0
  tuple: ^2.0.2
  qr_flutter: ^4.0.0
  slide_countdown: ^1.6.1
  json2dart_safe: ^1.5.8
  screenshot: ^3.0.0
  image_gallery_saver_plus: ^4.0.1
  permission_handler: ^11.3.1
  date_format: ^2.0.9
  flutter_smart_dialog: ^4.9.8
  install_plugin: ^2.1.0
  collection: ^1.18.0 # 有间接依赖到
  video_player_web_hls: ^1.3.0
  video_player_web: ^2.3.2
  file_picker: ^8.1.2
  photo_view: ^0.15.0
  background_app_bar: ^2.1.0
  city_pickers: ^1.3.0 # 城市选择器
  restart_app: ^1.2.1
  freezed_annotation: ^2.4.4 

  downloadsfolder: ^1.1.0
  dia_static: ^0.1.2
  device_uuid: ^0.0.4
  wakelock_plus: ^1.2.8
  connectivity_plus: ^6.1.0 #网络状态检测
  extended_nested_scroll_view: ^6.2.1
  media_kit: ^1.1.11 # Primary package.
  media_kit_video: ^1.2.5 # For video rendering.
  media_kit_libs_video: ^1.0.5 # Native video dependencies.
  flutter_keyboard_visibility: ^6.0.0
  image_picker: ^1.1.2
  expandable_richtext: ^1.0.7
  web_socket_client: ^0.2.0
  toastification: ^3.0.2
  wechat_assets_picker: ^9.5.0
  flutter_popup: ^3.3.4
  flutter_inappwebview: ^6.1.5
  webviewx_plus: ^0.5.1
  webview_flutter: ^4.8.0
  webview_flutter_wkwebview: ^3.14.0
  auto_size_text: ^3.0.0
  shelf: ^1.4.2
  web: ^1.1.1
  android_dynamic_icon: 2.0.0

  short_video_mudle:
    git:
      url: https://gitlab.qmpexevcqy.work/packages/short_video_mudle.git
      ref: 1.0.3
    # path: ../short_video_mudle
  http_service:
    git:
      url: https://gitlab.qmpexevcqy.work/packages/http_service.git
      ref: 1.0.1
    # path: ../http_service


dev_dependencies:
  # 生成器
  build_runner: ^2.4.9
  # 序列化
  json_serializable:
    ^6.8.0
    # 数据模型
  freezed: ^2.5.2
  hive_ce_generator: ^1.8.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  meta: ^1.14.0
  analyzer: "<7.4.0"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true
  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/app_default/
    - assets/images/community/
    - assets/images/tabbar/
    - assets/images/mine/
    - assets/images/mine/withdrawal/
    - assets/images/mine/vip/
    - assets/images/mine/app_icon/
    - assets/images/mine/message/
    - assets/images/search/
    - assets/images/player/
    - assets/images/ai/
    - assets/images/ann/
    - assets/images/ai/cloth/
    - assets/images/ai/face/
    - assets/images/ai/home/
    - assets/images/ai/record/
    - assets/images/ai/tab/
    - assets/images/shi_pin/
    - assets/images/community/
    - assets/images/home/
    - assets/images/reward/
analyzer:
  exclude:
    - lib/**/*.g.dart

  # plugins:
  #   - custom_lint
